- name: data types
  hosts: localhost
  vars:
    Course: Devops with AWS #string
    Tools: # list
    - Linux
    - Shell
    - Ansible 
    Experience: # map or directory
      Devops: 3 # Number
      AWS: 2 
      Docker: 1
    Realproject: true #boolean
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "Course: {{Course}}, Tools covered: {{Tools}}, Experience is: {{Experience}}, is
      real project: {{Realproject}}"